spring:
  application:
    name: todo-api
  datasource:
    url: jdbc:h2:mem:todoDB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/todoDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
